bcgov/jag-shuber-frontend

.s2i/bin/assemble
.s2i/bin/save-artifacts
Jenkinsfile
openshift/Readme.md
openshift/templates/nginx-frontend-template.yml
openshift/templates/shuber-app-environment.json

- Adding jenkins file
- s2i scripts
- nginx-frontend-template
Pulled some of these files / ideas from bcgov/tfrs

Adding OpenShift frontend tools template

---

.s2i/bin/assemble
Jenkinsfile
openshift/templates/frontend/frontend-build.json
openshift/templates/nginx-runtime/nginx-runtime-build.json

Managed to shave about 3 minutes off of the build by adding a few performance tweaks.

Build performance improvements

---

.vscode/launch.json
tsconfig.test.json

Adding the ability to debug our unit tests

Changing config and adding launch entry for debugging tests

---

.s2i/bin/assemble
.s2i/bin/save-artifacts
Jenkinsfile

Some changes to fix the build.

Build debugging

---

public/manifest.json
src/app/components/Timeline/Timeline.tsx
src/app/index.tsx
src/app/modules/assignments/components/AssignmentTimeline/AssignmentDropRow.tsx
src/app/pages/Timeline/index.tsx

- Changed zindex of drop areas so that they are above all items
- Added a tool window in the Timeline view

Polishing some aspects:

---

src/app/api/index.ts
src/app/modules/assignments/components/AssignmentTimeline/AssignmentTimelineCard.tsx
src/app/modules/assignments/dragdrop/AssignmentDragSource.tsx

A small bug fix to the drag and drop and some additional UI for how many sheriffs are needed

Assignment required sheriffs

---

README.md

Updated the ReadMe to reflect PR process and conventions

Updates to PR process and conventions

---

src/app/api/index.ts
src/app/components/AssignmentDetails.tsx
src/app/components/AssignmentForm.tsx
src/app/components/AssignmentTimeline/AssignmentTimelineCard.tsx
src/app/components/DateDisplay.tsx
src/app/components/FormElements/CourtroomSelector.tsx
src/app/components/FormElements/DateField.tsx
src/app/components/FormElements/DateTimeField.tsx
src/app/components/FormElements/DaysOfWeekChecklist.tsx
src/app/components/FormElements/NumberOfSheriffsSelector.tsx
src/app/components/FormElements/TimeField.tsx
src/app/components/SheriffTrainingDetails.tsx
src/app/containers/AddAssignmentModal.tsx
src/app/infrastructure/EnumUtils.ts
src/app/infrastructure/__tests__/EnumTest.ts
src/app/pages/DefaultAssignments.tsx

- Updated the AssignmentForm to accommodate the assignment template fields; currently used only for the Default Court Assignment
- Created components for weekday checklist
- Updated the date and time components to take default dates/times

Default court assignment form

---

src/app/containers/AssignmentTemplateEditForm.tsx
src/app/modules/assignments/reducer.ts
src/app/modules/assignments/selectors.ts

have to find the index based on the template id vs indexing based on the template id

Bug fix for indexing array of templates

---

.vscode/launch.json
config/jestSetup.js
config/paths.js
package.json
scripts/test.js
src/app/infrastructure/RequestAction.ts
src/app/infrastructure/__tests__/RequestActionTests.ts
src/app/infrastructure/__tests__/toTitleCaseTest.ts
src/app/store.ts
src/libs/redux-actions-assertions.d.ts
yarn.lock

This can hopefully become a cleaner pattern that we can use for the request/response type actions.

Request response pattern

---

src/app/api/Api.ts
src/app/api/Mock/MockApi.ts
src/app/api/Mock/MockData.ts
src/app/api/index.ts
src/app/components/AssignmentDefaultList.tsx
src/app/components/AssignmentForm.tsx
src/app/components/FormElements/JailRoleSelector.tsx

Added functionality to create, edit, save, and delete a default Jail Assignment.

Default jail assignments

---

.vscode/settings.json
src/app/api/Api.ts
src/app/api/Mock/MockApi.ts
src/app/api/Mock/MockData.ts
src/app/api/index.ts
src/app/api/utils.ts
src/app/components/AssignmentForm.tsx
src/app/components/FormElements/AlternateAssignmentSelector.tsx
src/app/components/FormElements/RunSelector.tsx
src/app/containers/AssignmentEditForm.tsx
src/app/modules/assignments/requests/assignments.ts

Adding functionality for the Other and Escort default assignments

Manage default assignments

---

Jenkinsfile

- Removing error message when deployment times out
- adding larger commit message to slack notifications

Updating jenkins pipeline messages

---

src/app/api/Api.ts
src/app/api/Mock/MockApi.ts
src/app/api/Mock/MockData.ts
src/app/components/FormElements/FormFieldWrapper.tsx
src/app/components/ScheduleShiftCopyForm.tsx
src/app/containers/ScheduleShiftCopyForm.tsx
src/app/containers/ScheduleShiftCopyModal.tsx
src/app/containers/ScheduleShiftCreateForm.tsx
src/app/modules/shifts/actions.ts
src/app/modules/shifts/reducer.ts
src/app/modules/shifts/requests/shifts.ts
src/app/pages/Scheduling.tsx
src/app/pages/pages.css

Added functionality to populate the current week's schedule from the previous week's schedule

Copy shifts previous week

---

src/app/api/utils.ts
src/app/components/FormElements/WorkSectionSelector.tsx
src/app/components/ScheduleShiftActionsPanel/ScheduleShiftActionPanel.css
src/app/components/ScheduleShiftActionsPanel/ScheduleShiftActionPanel.tsx
src/app/components/ScheduleShiftForm.tsx
src/app/components/SheriffDisplay.tsx
src/app/components/ShiftCard.tsx
src/app/containers/AssignmentDutyEditForm.tsx
src/app/containers/LongTermSchedule/LongTermSchedule.css
src/app/containers/LongTermSchedule/LongTermSchedule.tsx
src/app/containers/ScheduleShiftAddModal.tsx
src/app/containers/ScheduleShiftCreateForm.tsx
src/app/containers/ScheduleShiftEditForm.tsx
src/app/containers/ScheduleShiftEditModal.tsx
src/stories/Components/Schedule/ScheduleSummary.stories.tsx
src/stories/Components/Schedule/ShiftCard.stories.tsx

Adding functionality to edit a shift

Edit shift

---

src/app/infrastructure/EnumUtils.ts

Whoops - should have left that bit-wise operator in 👎

Adding the bit-wise operator back in for EnumUtils

---

.vscode/launch.json
package.json
scripts/test.js
src/app/api/Api.ts
src/app/api/Client.ts
src/app/api/Mock/MockApi.ts
src/app/api/__integration_tests__/api-assignment.tests.ts
src/app/api/__integration_tests__/api-duty.tests.ts
src/app/api/__integration_tests__/api-sheriff.tests.ts
src/app/api/__integration_tests__/crud-e2e-template.ts
src/app/api/__tests__/ApiUtilsTests.ts
src/app/api/__tests__/shape-matchers.ts
src/app/infrastructure/TestUtils.ts
src/app/infrastructure/__tests__/objectUtilsTests.ts
src/app/infrastructure/objectUtils.ts

- Split integration tests (can be run using yarn test-api)
- AssignmentDuty & SheriffDuty:
- Create, Delete, Read and Update are complete
- Tests have been written for all operations
- createDefaultDuties has been implemented and tested
- Get duties is implemented with startDate and EndDate
- Created some object utils for renaming keys in json (for api)

Let there be Duty Roster

---

src/app/modules/sheriffs/__tests__/SheriffSelector-tests.ts

- Removing unused import to fix build

Fixing Build

---

src/app/RootLayout.tsx
src/app/components/Navigation.tsx
src/app/components/ScheduleShiftForm.tsx
src/app/components/SheriffDisplay.tsx
src/app/components/ShiftSchedule.tsx
src/app/components/Timeline/Timeline.tsx
src/app/components/TimelineToolsPanel.tsx
src/app/containers/LongTermSchedule/LongTermSchedule.tsx
src/app/containers/ScheduleShiftEditForm.tsx

- Changed date format display on schedule 
- Bug fix on Sheriff Display to look for null and undefined
- Added Sheriff Selector to the Edit Shift form
- Updated order and labelling in nav bar

Schedule timeline visual enhancements

---

src/app/api/Api.ts
src/app/api/Client.ts
src/app/api/Mock/MockApi.ts
src/app/api/Mock/MockData.ts
src/app/components/AssignmentDutyCard/AssignmentDutyCard.tsx
src/app/components/AssignmentDutyForm.tsx
src/app/components/AssignmentDutyInformationPanel/AssignmentDutyInformationPanel.css
src/app/components/AssignmentDutyInformationPanel/AssignmentDutyInformationPanel.tsx
src/app/containers/AssignmentDutyCreateForm.tsx
src/app/containers/AssignmentDutyEditForm.tsx
src/app/containers/DutyRosterTimeline/DutyRosterTimeline.tsx
src/app/modules/assignments/actions.ts
src/app/modules/assignments/common.ts
src/app/modules/assignments/reducer.ts
src/app/modules/assignments/requests/assignmentDuties.ts
src/app/modules/assignments/selectors.ts

- can add comment to duty via duty edit form
- when  comment is added icon will appear on duty

Add comments to duties

---

src/app/components/AssignmentForm.tsx
src/app/containers/AssignmentAddModal.tsx
src/app/containers/AssignmentEditForm.tsx
src/app/containers/AssignmentEditModal.tsx

- added flags for disabling/enabling delete and save buttons
- updated modals to disable delete/save functionality

Disabling delete and save assignment

---

src/app/components/ScheduleSummary/ScheduleSummary.css
src/app/components/SheriffListCard/SheriffListCard.css
src/app/components/SheriffListCard/SheriffListCard.tsx
src/app/components/ShiftCard.tsx
src/app/components/WorkSectionIndicator/WorkSectionIndicator.css
src/app/components/WorkSectionIndicator/WorkSectionIndicator.tsx
src/app/containers/DutyRosterSheriffCard.tsx
src/app/infrastructure/colorUtils.ts
src/app/pages/Scheduling.tsx
src/app/store.ts

- adding work section indicator to sheriff card
- adding alias to sheriff card

Sheriff card detail updates

---

src/app/containers/SheriffRankDisplay.tsx
src/app/modules/courthouse/selectors.ts
src/app/modules/shifts/selectors.ts

- Fixing sheriff rank display
- ordering shifts by work section id

Ordering shifts

---

src/app/components/AssignmentDutyForm.tsx
src/app/components/AssignmentForm.tsx
src/app/components/ScheduleShiftCopyForm.tsx
src/app/components/ScheduleShiftForm.tsx
src/app/components/SheriffForm.tsx
src/app/modules/courthouse/selectors.ts

Fixing [367-sheriff-modal-data-entry](https://trello.com/c/qS0eZFxb/367-sheriff-modal-data-entry)

Bug Fix 367 sheriff modal data entry

---

.storybook/webpack.config.js
config/webpack.config.prod.js
package.json
yarn.lock

Hopefully fixing issues with svg loader

Fix showstopper

---

src/app/components/FormElements/TimePicker.tsx
yarn.lock

- updating api client
- updating time picker to send timezone information

Timezone bug fixes

---

src/app/components/Page/Page.css
src/app/index.css

Schedule should now print with headings on each page and without toolbar icons

fixing print schedule bugs

---

src/app/api/Api.ts
src/app/api/Client.ts
src/app/api/Mock/MockApi.ts
src/app/api/Mock/MockData.ts
src/app/api/index.ts
src/app/components/AssignmentDutyCard/AssignmentDutyCard.tsx
src/app/components/AssignmentDutyForm.tsx
src/app/containers/AssignmentDutyCreateForm.tsx
src/app/containers/AssignmentDutyEditForm.tsx
src/app/containers/DutyRosterTimeline/DutyRosterTimeline.tsx
src/app/infrastructure/Validators.ts
src/app/modules/assignments/actions.ts
src/app/modules/assignments/common.ts
src/app/modules/assignments/reducer.ts
src/app/modules/assignments/requests/assignmentDuties.ts
src/app/modules/assignments/selectors.ts
src/app/modules/user/actions.ts
yarn.lock

- adding frontend support for persisting duty comments

Saving duty comments

---

src/app/api/Api.ts
src/app/components/LeaveCancelledPopover.tsx
src/app/components/PartialLeavePopover.tsx
src/app/containers/DutyRosterSheriffCard.tsx
src/app/containers/SheriffProfile.tsx
src/app/containers/SheriffProfilePluginLeaves/LeavesFieldTable.tsx
src/app/containers/SheriffProfilePluginLeaves/SheriffProfilePluginLeaves.tsx
src/app/containers/SheriffProfilePluginLeaves/SheriffProfilePluginTraining.tsx
src/app/containers/TrainingLeaveSubCodeSelector.tsx
src/app/modules/leaves/selectors.ts

- adding support in sheriff profile to add time away for training 
- bug fix for adding training and leave to a net new sheriff profile

Record time away training

---

src/app/components/ScheduleControlPanelForm.tsx
src/app/containers/ScheduleControls.tsx
src/app/containers/ScheduleShiftAddModal.tsx
src/app/containers/SheriffProfilePluginLeaves/LeavesFieldTable.tsx
src/app/index.css
src/app/modules/schedule/actions.ts
src/app/modules/schedule/reducer.ts
src/app/modules/shifts/selectors.ts

- Fixed title on add shift modal (from 'Edit Shift' to 'Add Shift')
- Updated shift sort
- Added a Select All button to the Manage Schedule page

Shift bug fixes enhancements

---

Jenkinsfile

@cjam @hollyegrayson I have updated the Jenkinsfile. Please review and merge.

Updated Jenkinsfile for code error 'url: url:'

---

src/app/components/AssignmentSheriffDutyReassignmentForm.tsx
src/app/containers/AssignmentSheriffDutyReassignmentModal.tsx
src/app/containers/DutyRosterTimeline/DutyRosterTimeline.tsx
src/app/index.css

- updating the warning message in the sheriff reassignment modal when the user is dragging a sheriff duty (vs a sheriff) in the duty roster

Update warning on reassignment

---

src/app/components/AssignmentSheriffDutyReassignmentForm.tsx
src/app/containers/AssignmentEditModal.tsx

- clarified logic for warning messages when reassigning sheriffs
- updated the confirmation message for deleting a default assignment

Bug fix logic for warning

---

Jenkinsfile

Fixing Jenkins pipeline
- setting timeout to 7 DAYS

Setting time unit back to DAYS

---

src/app/containers/DutyRosterToolsForm/DutyRosterToolsForm.tsx
src/app/containers/SheriffScheduleDisplay.tsx
src/app/modules/assignments/requests/assignmentDuties.ts

Fixes a few small bugs:
Fixed Distribute Schedule: 
- Changed shift selector
Fixed DutyRosterTools:
- Both tools should be inactive
Changed success message when no duties are autoassigned

Auto assign bug fixes

---

Jenkinsfile

Fixing Pipeline errors
- Pulling out hashstring via different method
- adding changeString back to slack notifications

Pipeline fixes

---

src/app/api/Api.ts

just fixing jag-shuber-api import

---

Jenkinsfile.common.groovy
src/app/components/AssignmentForm.tsx

runId->escortRunId
jenkinsFile prod url point to prod

Small Fixes

---

src/app/components/AssignmentDefaultList.tsx
src/app/components/ConfirmationModal.tsx
src/app/components/Legend/Symbols.tsx
src/app/components/ScheduleDeputyViewList.tsx
src/app/components/ScheduleSummary/ScheduleSummary.tsx
src/app/components/ShiftSchedule.tsx
src/app/containers/DutyRosterTimeline/DutyRosterTimeline.tsx

Fixes timeline alignment issue with workaround
Fixes timeline alignment issue when scrollbars are active
Fixes timeline not parsing visibleTimeStart and visibleTimeEnd props
Refactored several reactJS anti-pattern warnings (missing keys for duplicated elements)
- Left commented code about the current work arounds

Bug jira ss17

---

src/app/containers/AssignmentDutyCreateForm.tsx
src/app/containers/AssignmentDutyEditForm.tsx
src/app/containers/DutyRosterTimeline/DutyRosterTimeline.tsx
src/app/modules/assignments/actions.ts

Split duties when assigning a sheriff based on shifts

Implemented Splitting duties when assigning a sheriff based on shifts

---

src/app/containers/DutyRosterTimeline/DutyRosterTimeline.css
src/app/containers/DutyRosterTimeline/DutyRosterTimeline.tsx

Added warning message when assigning sheriffs outside of shift

---

src/app/containers/DutyRosterTimeline/DutyRosterTimeline.tsx

Replaced assignment out of shift message

---

src/app/components/AssignmentForm.tsx
src/app/components/ScheduleShiftForm.tsx
src/app/containers/ScheduleShiftCreateForm.tsx

Create assignments when managing shifts

Display all assignment types when adding a shift

---

src/app/RootLayout.tsx
src/app/api/Api.ts
src/app/api/Mock/MockData.ts
src/app/components/AssignmentForm.tsx
src/app/components/AssignmentSchedule.tsx
src/app/components/AssignmentScheduleCard.tsx
src/app/components/Navigation.tsx
src/app/containers/AssignmentScheduleAddModal.tsx
src/app/containers/AssignmentScheduleControls.tsx
src/app/containers/AssignmentScheduleCreateForm.tsx
src/app/containers/AssignmentTemplateCreateForm.tsx
src/app/containers/FutureAssignment/FutureAssignment.css
src/app/containers/FutureAssignment/FutureAssignment.tsx
src/app/modules/assignmentSchedule/actions.ts
src/app/modules/assignmentSchedule/reducer.ts
src/app/modules/assignmentSchedule/selectors.ts
src/app/modules/system/action.ts
src/app/pages/Assignments.tsx
src/app/store.ts

Added new "Add Assignment" page

---

src/app/RootLayout.tsx
src/app/containers/AssignmentScheduleControls.tsx
src/app/containers/AssignmentScheduleEditModal.tsx
src/app/containers/FutureAssignment/FutureAssignment.tsx
src/app/modules/assignmentSchedule/selectors.ts

Fixed assignment schedule cards by number of sheriffs required
Added ability to edit scheduled assignments

Bug jira ss33

---

src/app/modules/assignmentSchedule/selectors.ts

Fixed assignments filter by visible time not matching because of tmz

---

src/app/modules/assignmentSchedule/selectors.ts

Fixed time comparison issue

---

src/app/api/Api.ts
src/app/api/Client.ts
src/app/containers/AssignmentEditModal.tsx
src/app/modules/assignments/requests/assignments.ts

Fixed deleting multiple assignments

---

src/app/components/Navigation.tsx
src/app/components/NavigationDropDown.tsx

Fixed menu item not highlighted when it is a drop down

---

src/app/components/NavigationDropDown.tsx

Refactored NavigationDropDown: removed unused logs

---

src/app/containers/DutyRosterTimeline/DutyRosterTimeline.tsx

Fixed duty roster displaying assignments for wrong week days

---

src/app/components/AssignmentForm.tsx
src/app/containers/AssignmentAddModal.tsx
src/app/containers/AssignmentEditForm.tsx
src/app/containers/AssignmentEditModal.tsx
src/app/containers/AssignmentScheduleAddModal.tsx
src/app/containers/AssignmentScheduleControls.tsx
src/app/containers/AssignmentScheduleEditModal.tsx
src/app/containers/AssignmentTemplateCreateForm.tsx

Added duplicated assignment check

---

src/app/api/Api.ts
src/app/containers/AssignmentCourtTypeSelector.tsx
src/app/containers/LongTermSchedule/LongTermSchedule.tsx
src/app/containers/SheriffScheduleDisplay.tsx
src/app/modules/assignmentSchedule/selectors.ts
src/app/modules/assignments/selectors.ts
src/app/modules/shifts/selectors.ts

Sorting of cards by criteria defined in case ss-35

Change sorting order of cards and assignment dropdowns

---

src/app/api/Api.ts
src/app/components/ShiftSchedule.tsx

Add grouping of shifts

---

src/app/components/AssignmentSchedule.tsx
src/app/components/ShiftSchedule.tsx

Add grouping to Add Assignments

---

package.json
src/app/containers/DutyRosterTimeline/DutyRosterTimeline.tsx

Upgrade timeline component

---

src/app/containers/DutyRosterTimeline/DutyRosterTimeline.tsx
src/app/modules/assignmentSchedule/selectors.ts

Fixed Add assignment not displaying minutes ss-47
Fixed outside of shift check ss-44

Fixed outside of shift check

---

docker/manage

- Don't automatically exit on errors.

Update docker manage script

---

openshift/templates/nginx-runtime/nginx.conf.template
src/app/api/Client.ts
src/app/modules/user/requests.ts
yarn.lock

@WadeBarnes 
- changed request interceptor to append auth token to request header

Changed the auth process to read token from request header

---

src/app/api/Client.ts
src/app/components/Form/FormContainer.tsx
src/app/components/SheriffProfile/SheriffProfilePlugin.tsx
src/app/containers/SheriffProfilePluginLeaves/SheriffProfilePluginLeaves.tsx
src/app/containers/SheriffProfilePluginLeaves/SheriffProfilePluginTraining.tsx
src/app/containers/SheriffProfilePluginLocation/SheriffProfilePluginLocation.tsx
src/app/infrastructure/Validators.ts
src/app/modules/user/requests.ts

Merge in updates to Sheriff Locations from feature/sheriff-locations.

---

src/app/containers/SheriffProfileModal.tsx

Fix SheriffProfileModal cancel button.

---

src/app/RootLayout.tsx
src/app/api/Client.ts
src/app/components/Navigation.tsx
src/app/index.tsx
src/app/modules/system/action.ts
src/app/modules/user/actions.ts
src/app/modules/user/requests.ts
src/app/store.ts

Complete auth implementation, update application initialization where required now that token issues have been fixed.

Auth and app initialization updates.

---

src/app/modules/user/requests.ts

We don't need the smsessionCookie check any more in UserTokenRequest.doWork

We don't need the smsessionCookie check any more in UserTokenRequest.doWork

---

src/app/components/Navigation.tsx
src/app/containers/SheriffListGrid.tsx
src/app/containers/SheriffListList.tsx
src/app/containers/SheriffLoanIcon.tsx
src/app/containers/SheriffProfileModal.tsx
src/app/modules/sheriffs/selectors.ts
src/app/plugins/AdminRoles/AdminAssignUserRoles.tsx
src/app/plugins/AdminUsers/AdminUsers.tsx

Clean up sheriff current location implementation.

---

src/app/containers/SheriffLoanIcon.tsx
src/app/modules/sheriffs/selectors.ts

Fix a couple display bugs with SheriffLoanIcon and related selectors.

---

src/app/components/AdminForm/AdminForm.tsx
src/app/containers/AdminForm.tsx
src/app/plugins/AdminAssignmentTypes/AdminCourtrooms.tsx

Turn redux-form touchOnBlur and touchOnChange to true, they weren't required to fix the cursor jump / re-rendering issues and they need to be turned off to get expiry buttons etc. working again.

Admin form datatable rendering fixes.

---

src/app/components/AdminForm/AdminForm.tsx
src/app/components/Table/DataTable.tsx
src/app/containers/AdminForm.tsx

Tweaks to AdminForm and DataTable.

---

src/app/plugins/AdminRoles/AdminFrontendScopes.tsx
src/app/plugins/AdminRoles/AdminRoles.tsx
src/app/plugins/AdminRoles/AdminUsers.tsx

Fixes a couple regressions in handlers following design changes to DataTable and other common components.

Fixes for a couple AdminForm and DataTable onButtonClicked handlers.

---

src/app/components/Form/FormContainer.tsx
src/app/components/Page/Page.tsx
src/app/containers/AdminForm.tsx
src/app/containers/SheriffProfilePluginLocation/SheriffProfilePluginLocation.tsx
src/app/modules/users/selectors.ts
src/app/plugins/AdminAssignmentTypes/AdminCourtRoles.tsx
src/app/plugins/AdminAssignmentTypes/AdminCourtrooms.tsx
src/app/plugins/AdminAssignmentTypes/AdminEscortTypes.tsx
src/app/plugins/AdminAssignmentTypes/AdminJailRoles.tsx
src/app/plugins/AdminAssignmentTypes/AdminOtherTypes.tsx
src/app/plugins/AdminAssignmentTypes/WorkSectionsLayout.tsx
src/app/plugins/AdminLeaveTypes/AdminLeaveTypes.tsx
src/app/plugins/AdminLeaveTypes/AdminTrainingTypes.tsx
src/app/plugins/AdminRoles/AdminApiScopes.tsx
src/app/plugins/AdminRoles/AdminFrontendScopes.tsx
src/app/plugins/AdminRoles/AdminRoles.tsx
src/app/plugins/AdminRoles/AdminUsers.tsx
src/app/plugins/AdminRoles/containers/AdminEffectivePermissionsModal.tsx
src/app/plugins/AdminRoles/containers/FrontendScopeSelector.tsx
src/app/registerServiceWorker.ts

- Replace old diff (deep-object-diff package) mechanisms in FormContainer with new custom logic for getDataFromFormValues. 
- Update plugin onSubmit handlers to reflect changes to FormContainer. Improves form submission, fixes issue where records that were not 'dirty' (added / changed / deleted) were being included in updates due to how deep-object-diff was calculating array differences.

Refactor Admin Form (FormComponent) getDataFromFormValues.

---

src/app/containers/SheriffLoanIcon.tsx
src/app/containers/SheriffProfilePluginLocation/SheriffProfilePluginLocation.tsx
src/app/modules/sheriffs/selectors.ts

SheriffProfilePluginLocation sheriff list refreshing.

Push fix for SheriffProfilePluginLocation sheriff list refreshing.

---

src/app/plugins/AdminAssignmentTypes/AdminCourtrooms.tsx
src/app/plugins/AdminAssignmentTypes/AdminEscortTypes.tsx
src/app/plugins/AdminAssignmentTypes/AdminJailRoles.tsx
src/app/plugins/AdminAssignmentTypes/AdminOtherTypes.tsx
src/app/plugins/AdminLeaveTypes/AdminLeaveTypes.tsx
src/app/plugins/AdminLeaveTypes/AdminTrainingTypes.tsx

Remove code that was duplicated in merge.

---

src/app/components/FormElements/DateField.tsx

Update DateField FormElement to use UTC dates by default.

---

src/app/containers/SheriffLoanIcon.tsx
src/app/containers/SheriffProfile.tsx
src/app/modules/sheriffs/selectors.ts

-  Display sheriff location icon 7 days before the sheriff is actually on loan.
- Use 24 hour time format for partial day display.

Sheriff location display fixes.

---

src/app/components/FormElements/DateField.tsx
src/app/containers/SheriffLoanIcon.tsx
src/app/containers/SheriffProfile.tsx
src/app/containers/SheriffProfilePluginLocation/SheriffProfilePluginLocation.tsx
src/app/infrastructure/Validators.ts
src/app/modules/sheriffs/selectors.ts

More changes for sheriff locations.

---

src/app/containers/DutyRosterTimeline/DutyRosterTimeline.tsx
src/app/modules/sheriffs/selectors.ts

Correct typo in 7 day proceedure.

---

package.json
src/app/api/Api.ts
src/app/api/Client.ts
src/app/components/ShiftSchedule.tsx
src/app/containers/DutyRosterControls.tsx
src/app/containers/ScheduleControls.tsx
src/app/containers/SheriffLoanIcon.tsx
src/app/modules/sheriffs/requests.ts
src/app/modules/sheriffs/selectors.ts
src/app/pages/DutyRoster.tsx
yarn.lock

Changes for sheriff locations and integration with timeline controls.

---

src/app/containers/ScheduleSummary.tsx

Tweak ScheduleSummary indicators.

---

src/app/components/AdminForm/AdminForm.tsx
src/app/components/Table/DataTableTable.tsx
src/app/pages/ManageAssignmentTypes.tsx
src/app/plugins/AdminAssignmentTypes/AdminCourtRoles.tsx
src/app/plugins/AdminAssignmentTypes/WorkSectionsLayout.tsx

Resolving SS-84, SS-88, SS-89
